name: Push to DI

on:
  #push
  workflow_dispatch:
jobs:
 
  build:

    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
        days: ${{ vars.DAYS }}
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    #- run: sh pushIssues.sh $days
    #- run: cat issues.json
    #- run: sh pushCommits.sh $days
    #- run: cat commits.json
    #- run: sh pushPRDetails.sh $days
    #- run: cat prs.json
    - run: sh pushAlerts.sh 
    - run: cat alerts.json
